data:extend{
  {
    type = "custom-input",
    name = "mis-cycle-module-forwards",
    key_sequence = "SHIFT + mouse-wheel-up",
    controller_key_sequence = "CONTROL + controller-dpup",
    --linked_game_control = "cycle-blueprint-forwards",
    order = "b",
    --consuming = "game-only",
  },
  {
    type = "custom-input",
    name = "mis-cycle-module-backwards",
    key_sequence = "SHIFT + mouse-wheel-down",
    controller_key_sequence = "CONTROL + controller-dpdown",
    --linked_game_control = "cycle-blueprint-backwards",
    order = "c",
    --consuming = "game-only",
  },
  {
    type = "custom-input",
    name = "mis-give-module-inserter",
    key_sequence = "ALT + M",
    localised_name = { "shortcut-name.mis-give-module-inserter" },
    order = "a",
  },
  {
    type = "shortcut",
    name = "mis-give-module-inserter",
    order = "b[blueprints]-i[module-inserter]",
    action = "lua",
    associated_control_input = "mis-give-module-inserter",
    --technology_to_unlock = "construction-robotics",
    style = "green",
    icon = "__ModuleInserterSimplified__/graphics/module-inserter-x32-white.png",
    icon_size = 32,
    small_icon = "__ModuleInserterSimplified__/graphics/module-inserter-x32-white.png",
    small_icon_size = 32,
  },
}
